@startuml
digraph G {
    node [
        shape = record, 
        fillcolor = Orange, 
        style = "filled, rounded",
        ]

    1 [label = "Document Review"]
    2 [label = "Open Source Intelgence"]
    3 [label = "Interviews"]
    4 [label = "Document Review"]
    5 [label = "Open Source Intelgence"]
    6 [label = "Followup Questions"]

    1 -> 2 -> 3 -> 4:n, 5:n
    4:s, 5:s -> 6
}
@enduml
