
@startuml
digraph G {
    rankdir=LR
    node [shape=record, fillcolor=lightgrey, style="filled,rounded"]
    1 [label = "1 - A&E Control System Architectures"]
    1 -> 2,3,4,5,8,9
    
    subgraph cluster0 {
        label = "Production Assessments"
        fontsize = 20
        style = "filled,rounded"
        color = LightGreen

        2 [label = "2 - A&E Control Network Captures"]
        3 [label = "3 - A&E Production Control Networks"]
    }

    subgraph cluster1 {
        label = "Lab Assessments (not safe for production systems)"
        fontsize = 20
        style = "filled,rounded"
        color = Yellow

        4 [label = "4 - A&E Controller Logic"]
        5 [label = "5 - A&E Control Protocols"]
        6 [label = "6 - A&E Proprietary Serial Protocols"]
        7 [label = "7 - A&E Proprietary RF Protocols"]
        8 [label = "8 - A&E Embedded Memory"]
        9 [label = "9 - A&E Embedded Firmware"]

        5 -> 6,7
    }
}
@enduml
