@startuml
digraph G {
    node [
        shape = record, 
        fillcolor = Orange, 
        style = "filled, rounded"]

    1 [label = "Traffic Capture"]
    subgraph cluster0 {
        label = "Same as A&E\nControl Network Captures"
        labeljust = left
        style = "filled, rounded"
        color = deepskyblue

        2 [label="Endpoint and Flow Analysis"]
        3 [label = "Known Protocol Analysis"]
        4 [label = "Unknown Protocol Decode"]
    }
    5 [label = "Protocol Enumeration"]
    6 [label = "Protocol Fuzzing"]
    7 [label = "Protocol Exploitation"]

    1 -> 2 -> 3:n, 4:n
    3:s,4:s -> 5 -> 6 -> 7
}
@enduml
