@startuml
digraph G {
    node [
        shape = record, 
        fillcolor = Orange, 
        style = "filled, rounded",
        ]

    1 [label = "Controller Tag Analysis"]
    2 [label = "Controller Logic Analysis"]
    3 [label = "HMI Functional Analysis"]
    4 [label = "HMI Modification"]
    5 [label = "Testing Harness Creation"]
    6 [label = "Logic Flaw Testing"]

    1 -> 2 -> 3:n, 5:n
    3 -> 4:n
    4:s, 5:s -> 6
}
@enduml
